import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Check, FileCheck2, RefreshCw, ShieldAlert } from "lucide-react";
import type {
  CommandErrorDto, DecisionActionDto, DecisionExecutionDto, DecisionInboxDto,
  DecisionPreviewDto, EvidenceItemDto, RecoveryPreviewDto, RecoveryResultDto,
  RepositorySnapshotDto, VerificationImportPreviewDto, VerificationMethodDto,
  VerificationPreviewDto, VerificationResultDto,
} from "./contracts/generated/ipc";
import { Badge } from "./components/ui/badge";
import { Button } from "./components/ui/button";
import { workbench } from "./lib/workbench";

function short(value: string | null | undefined, length = 14) { return value ? value.slice(0, length) : "not reported"; }
function errorOf(value: unknown): CommandErrorDto { if (typeof value === "object" && value !== null && "message" in value) { const item = value as Partial<CommandErrorDto>; return { kind: item.kind ?? "unknown", message: String(item.message), detail: item.detail ?? null }; } return { kind: "unknown", message: String(value), detail: null }; }
function lines(value: string) { return value.split("\n").map((item) => item.trim()).filter(Boolean); }

export function TrancheThree({ snapshot, evidence, onRepositoryChanged }: { snapshot: RepositorySnapshotDto; evidence: EvidenceItemDto[]; onRepositoryChanged: () => Promise<void> }) {
  const [busy, setBusy] = useState(false); const [error, setError] = useState<CommandErrorDto | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const [inbox, setInbox] = useState<DecisionInboxDto | null>(null); const [proposal, setProposal] = useState("");
  const [method, setMethod] = useState<VerificationMethodDto | null>(null); const [verifier, setVerifier] = useState("verifier:reviewer");
  const [outcome, setOutcome] = useState("pass"); const [independent, setIndependent] = useState(""); const [shared, setShared] = useState(""); const [nonclaims, setNonclaims] = useState("Scientific acceptance or Standing.");
  const [outputs, setOutputs] = useState<string[]>([]); const [verificationPreview, setVerificationPreview] = useState<VerificationPreviewDto | null>(null); const [verificationResult, setVerificationResult] = useState<VerificationResultDto | null>(null);
  const [importPreview, setImportPreview] = useState<VerificationImportPreviewDto | null>(null);
  const [action, setAction] = useState<DecisionActionDto>("accept"); const [reason, setReason] = useState(""); const [performer, setPerformer] = useState("agent:reviewer"); const [sessionRef, setSessionRef] = useState(""); const [decisionPreview, setDecisionPreview] = useState<DecisionPreviewDto | null>(null); const [decisionResult, setDecisionResult] = useState<DecisionExecutionDto | null>(null);
  const [recoveryPreview, setRecoveryPreview] = useState<RecoveryPreviewDto | null>(null); const [recoveryResult, setRecoveryResult] = useState<RecoveryResultDto | null>(null);
  const current = useMemo(() => inbox?.entries.find((entry) => entry.proposal_id === proposal) ?? inbox?.entries[0] ?? null, [inbox, proposal]);
  const supported = snapshot.classification === "vela_repository" && snapshot.vela.binary?.state === "signed_runtime_baseline";
  useEffect(() => { setInbox(null); setVerificationPreview(null); setImportPreview(null); setDecisionPreview(null); setRecoveryPreview(null); }, [snapshot.path, snapshot.git.head_commit, snapshot.git.head_tree]);
  function guard(task: () => Promise<void>) { setBusy(true); setError(null); setNotice(null); task().catch((value) => setError(errorOf(value))).finally(() => setBusy(false)); }
  function refresh() { guard(async () => { const value = await workbench.refreshDecisionInbox(snapshot.path); setInbox(value); setProposal((old) => value.entries.some((entry) => entry.proposal_id === old) ? old : value.entries[0]?.proposal_id ?? ""); setVerificationPreview(null); setDecisionPreview(null); }); }
  function chooseMethod() { guard(async () => { const value = await workbench.selectVerificationMethod(snapshot.path); if (value) { setMethod(value); setVerifier(value.attested_by_actor_id ?? verifier); setNonclaims(value.does_not_establish.join("\n")); setVerificationPreview(null); } }); }
  function toggleOutput(path: string) { setOutputs((old) => old.includes(path) ? old.filter((item) => item !== path) : [...old, path]); setVerificationPreview(null); }
  function previewVerification() { if (!method || !current) return; guard(async () => setVerificationPreview(await workbench.previewVerificationRecord(snapshot.path, { proposal_id: current.proposal_id, profile: method.profile, method, property: method.property || null, complementary: false, outcome, does_not_establish: lines(nonclaims), independent_of: lines(independent), shared_dependencies: lines(shared), output_paths: outputs, actor: verifier }))); }
  function recordVerification() { if (!verificationPreview) return; guard(async () => { const value = await workbench.recordVerification(verificationPreview); if (value) { setVerificationResult(value); setVerificationPreview(null); await onRepositoryChanged(); setInbox(null); } else setNotice("Verification cancelled before Vela execution; no record was requested."); }); }
  function chooseImport() { guard(async () => { const value = await workbench.selectVerificationImport(snapshot.path); if (value) setImportPreview(value); }); }
  function importVerification() { if (!importPreview) return; guard(async () => { const value = await workbench.importVerification(importPreview); if (value) { setVerificationResult(value); setImportPreview(null); await onRepositoryChanged(); setInbox(null); } else setNotice("Verification import cancelled before Vela execution; no record was requested."); }); }
  function previewAuthority() { if (!current) return; guard(async () => setDecisionPreview(await workbench.previewDecision(snapshot.path, { proposal_id: current.proposal_id, entry_root: current.entry_root, action, reason, performer, session_ref: sessionRef.trim() || null }))); }
  function decide() { if (!decisionPreview) return; guard(async () => { const value = await workbench.executeDecision(decisionPreview); if (value) { setDecisionResult(value); setDecisionPreview(null); await onRepositoryChanged(); setInbox(null); } else setNotice("Decision cancelled before Vela execution; Repository state was not requested to move."); }); }
  const recoverable = verificationResult?.refusal?.code === "repository_incomplete" ? verificationResult.refusal.operation_id : decisionResult?.refusal?.code === "repository_incomplete" ? decisionResult.refusal.operation_id : null;
  function previewRecover() { if (!recoverable) return; guard(async () => setRecoveryPreview(await workbench.previewRecovery(snapshot.path, recoverable))); }
  function recover() { if (!recoveryPreview) return; guard(async () => { const value = await workbench.recoverTransaction(recoveryPreview); if (value) { setRecoveryResult(value); setRecoveryPreview(null); await onRepositoryChanged(); setInbox(null); } else setNotice("Recovery cancelled; no recovery command was requested."); }); }
  if (!supported) return <section className="inline-refusal"><AlertTriangle /><div><strong>Check and Decision actions unavailable</strong><p>Select a Vela Repository and the exact signed v0.977.2 runtime. Git and source tools remain separate.</p></div></section>;
  return <div className="surface-stack">{error && <section className="refusal" role="alert"><AlertTriangle /><div><strong>Action refused · {error.kind}</strong><p>{error.message}</p></div></section>}{notice && <section className="inline-refusal" role="status"><div><strong>Cancelled</strong><p>{notice}</p></div></section>}
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Current-task derived view</p><h2>Decision Inbox</h2></div><Button variant="secondary" onClick={refresh} loading={busy}><RefreshCw size={13}/>Refresh exact roots</Button></div>
      {!inbox ? <div className="teaching-empty"><FileCheck2/><strong>Inbox not read</strong><p>Refresh explicitly. No Proposal, Verification, objection, Decision, or Standing is inferred from stale UI state.</p></div> : inbox.refusal ? <div className="inline-refusal"><AlertTriangle/><div><strong>{inbox.refusal.code ?? inbox.refusal.kind}</strong><p>{inbox.refusal.message}</p></div></div> : <><dl className="fact-grid compact"><div className="fact"><dt>Task</dt><dd>{inbox.task}</dd></div><div className="fact"><dt>Repository root</dt><dd className="mono">{inbox.repository_root}</dd></div><div className="fact"><dt>Projection root</dt><dd className="mono">{inbox.projection_root}</dd></div><div className="fact"><dt>Observed</dt><dd>{new Date(inbox.observed_at_unix_ms).toLocaleString()}</dd></div></dl><p className="boundary-copy">Included: {inbox.included_records.length} exact current records. Omission: {inbox.omissions.join(" ")}</p><label className="field"><span>Current Proposal</span><select value={current?.proposal_id ?? ""} onChange={(event) => { setProposal(event.target.value); setDecisionPreview(null); setVerificationPreview(null); }}><option value="">No pending Proposal</option>{inbox.entries.map((entry) => <option value={entry.proposal_id} key={entry.entry_root}>{entry.proposal_id} · {entry.protocol_gate}</option>)}</select></label></>}
    </section>
    <section className="section-block review-columns"><div className="draft-form"><div className="section-heading"><div><p className="eyebrow">Scoped Check</p><h2>Record a scoped Verification</h2></div><Badge>authority effect: none</Badge></div><Button variant="secondary" onClick={chooseMethod} disabled={!current}>Choose retained Method</Button>{method && <><dl className="fact-grid compact"><div className="fact"><dt>Method</dt><dd className="mono">{method.repository_relative_path} · {short(method.sha256)}</dd></div><div className="fact"><dt>Performer</dt><dd>{method.reviewer_kind ?? "legacy"} · {method.reviewer_display_name ?? method.reviewer_identifier}</dd></div><div className="fact"><dt>Provider / version</dt><dd>{method.provider ?? "not exposed"} · {method.version ?? "not exposed"}</dd></div><div className="fact"><dt>Property</dt><dd>{method.property}</dd></div></dl><div className="form-row"><label className="field"><span>Attesting actor</span><input value={verifier} onChange={(event) => setVerifier(event.target.value)}/></label><label className="field"><span>Outcome</span><select value={outcome} onChange={(event) => setOutcome(event.target.value)}><option>pass</option><option>fail</option><option>inconclusive</option><option>error</option></select></label></div><label className="field"><span>Declared independent of (one actor per line)</span><textarea value={independent} onChange={(event) => setIndependent(event.target.value)} placeholder="agent:producer"/></label><label className="field"><span>Shared dependencies (one per line)</span><textarea value={shared} onChange={(event) => setShared(event.target.value)} placeholder="Same model provider, host, source, or toolchain"/></label><label className="field"><span>Does not establish</span><textarea value={nonclaims} onChange={(event) => setNonclaims(event.target.value)}/></label><fieldset className="artifact-fieldset"><legend>Explicit retained review outputs</legend>{evidence.map((item) => item.source.source === "local_file" && <label key={item.sha256}><input type="checkbox" checked={outputs.includes(item.source.repository_relative_path)} onChange={() => toggleOutput(item.source.source === "local_file" ? item.source.repository_relative_path : "")}/><span><strong>{item.display_name}</strong><small>{item.sha256}</small></span></label>)}</fieldset><Button onClick={previewVerification} disabled={!method || !current || !verifier || !lines(nonclaims).length}>Review exact Verification argv</Button></>}</div>
      <div className="draft-review">{verificationPreview ? <div className="review-panel"><Badge>non-authoritative</Badge><h3>{verificationPreview.draft.method.profile}</h3><pre className="argv-view">{verificationPreview.argv.map((item) => JSON.stringify(item)).join(" ")}</pre><p>{verificationPreview.warning}</p><Button onClick={recordVerification}>Record after native confirmation</Button></div> : <div className="teaching-empty"><FileCheck2/><strong>No Verification preview</strong><p>Actor difference is never treated as independence. Method, outputs, environment, disclosure, Proposal, and roots are rechecked after confirmation.</p></div>}</div></section>
    <section className="section-block handoff-block"><div><p className="eyebrow">Portable verifier boundary</p><h2>Import signed Verification</h2><p>Exact envelope bytes and current subject bindings are reviewed before the signed CLI verifies and retains them.</p></div><Button variant="secondary" onClick={chooseImport}>Choose signed envelope</Button></section>
    {importPreview && <section className="section-block review-panel"><h3>{importPreview.verification_record_id}</h3><dl className="fact-grid compact"><div className="fact"><dt>Verifier</dt><dd>{importPreview.verifier}</dd></div><div className="fact"><dt>Method</dt><dd>{importPreview.method_profile} · {importPreview.environment_root}</dd></div><div className="fact"><dt>Current subject</dt><dd className="mono">{importPreview.proposal_id} · {importPreview.current_repository_root}</dd></div><div className="fact"><dt>Independence</dt><dd>{importPreview.declared_independent_of.join(", ") || "none declared"}</dd></div><div className="fact"><dt>Shared dependencies</dt><dd>{importPreview.shared_dependencies.join(", ") || "none disclosed"}</dd></div></dl><p>{importPreview.warning}</p><Button onClick={importVerification}>Import after native confirmation</Button></section>}
    {verificationResult && <section className="section-block success-receipt" aria-live="polite">{verificationResult.refusal ? <AlertTriangle/> : <Check/>}<div><p className="eyebrow">Verification outcome</p><h2>{verificationResult.verification_record_id ?? verificationResult.refusal?.code ?? verificationResult.refusal?.kind}</h2><p>Outcome: {verificationResult.outcome ?? "not retained"}. Accepted Event delta: {verificationResult.accepted_event_delta ?? "not reported"}. Standing remains separate.</p>{verificationResult.refusal && <p>{verificationResult.refusal.message}</p>}</div></section>}
    <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Repository authority</p><h2>Attributed accept or reject</h2></div><Badge tone="warning">authority-changing</Badge></div>{!current ? <div className="teaching-empty"><ShieldAlert/><strong>No current Proposal selected</strong><p>Refresh the Inbox after Verification. No queue or durable Workbench state is created.</p></div> : <><dl className="fact-grid compact"><div className="fact"><dt>Proposal / Submission</dt><dd className="mono">{current.proposal_id} · {short(current.submission_root)}</dd></div><div className="fact"><dt>Entry root</dt><dd className="mono">{current.entry_root}</dd></div><div className="fact"><dt>Protocol gate</dt><dd>{current.protocol_gate} · {current.blockers.length} blockers</dd></div><div className="fact"><dt>Standing effect</dt><dd>{current.standing_delta.transition}</dd></div></dl>{current.blockers.map((blocker) => <div className="inline-refusal" key={`${blocker.code}:${blocker.subject}`}><AlertTriangle/><div><strong>{blocker.code}</strong><p>{blocker.detail}</p>{blocker.subject && <small>Subject: {blocker.subject}</small>}</div></div>)}<div className="form-row"><label className="field"><span>Decision</span><select value={action} onChange={(event) => { setAction(event.target.value as DecisionActionDto); setDecisionPreview(null); }}><option value="accept">accept</option><option value="reject">reject</option></select></label><label className="field"><span>Performer</span><input value={performer} onChange={(event) => setPerformer(event.target.value)}/></label></div><label className="field"><span>Bounded scientific reason</span><textarea value={reason} onChange={(event) => setReason(event.target.value)}/></label><label className="field"><span>Optional Entire/source-owned session reference</span><input value={sessionRef} onChange={(event) => setSessionRef(event.target.value)}/></label><Button onClick={previewAuthority} disabled={!reason.trim() || !performer.trim()}>Review exact attributed Decision</Button></>}
      {decisionPreview && <div className="review-panel authority-preview"><div className="trust-warning"><ShieldAlert/><p>{decisionPreview.warning}</p></div><dl className="fact-grid compact"><div className="fact"><dt>Performer</dt><dd>{decisionPreview.request.performer} · {decisionPreview.performer_kind}</dd></div><div className="fact"><dt>Repository principal</dt><dd>{decisionPreview.repository_authority_principal}</dd></div><div className="fact"><dt>Authentication / signer</dt><dd>{decisionPreview.authentication} / {decisionPreview.transaction_signer}</dd></div><div className="fact"><dt>Expected successor</dt><dd className="mono">{decisionPreview.expected_successor.repository_root}</dd></div></dl><h3>Verification observations remain separate</h3>{decisionPreview.entry.verifications.map((item) => <article className="verification-card" key={item.verification_record_root}><strong>{item.outcome} · {item.method_profile}</strong><p>{item.performer_kind ?? "legacy"} · {item.performer_identifier ?? item.verifier} · {item.provider ?? "provider not exposed"} · {item.version ?? "version not exposed"}</p>{item.method_metadata_status !== "verified_current" && <small className="state-error">Current retained Method metadata is unavailable or does not match the signed environment root; provider, version, and performer details are not inferred.</small>}<small>Property: {item.property}</small><small>Declared independent of: {item.declared_independent_of.join(", ") || "none"}</small><small>Shared dependencies: {item.shared_dependencies.join(", ") || "none disclosed"}</small><code>{item.verification_record_root}</code></article>)}<pre className="argv-view">{decisionPreview.argv.map((item) => JSON.stringify(item)).join(" ")}</pre><Button onClick={decide}>Execute after native confirmation</Button></div>}
    </section>
    {decisionResult && <section className="section-block success-receipt" aria-live="polite">{decisionResult.decision_committed ? <Check/> : <AlertTriangle/>}<div><p className="eyebrow">Actual Decision / Event / Standing readback</p><h2>{decisionResult.readback.status}</h2><p>Command success: {String(decisionResult.command_succeeded)}. Decision committed: {String(decisionResult.decision_committed)}. Verification outcome is not this Standing.</p><p>Expected successor matched: {String(decisionResult.successor_matches_preview)}. Receipt events matched readback: {decisionResult.events_match_receipt === null ? "receipt unavailable" : String(decisionResult.events_match_receipt)}.</p><p>Performer: {decisionResult.actual_performer ?? "not reported"}. Principal: {decisionResult.actual_authority_principal ?? "not reported"}.</p><p>Decision Event: {decisionResult.readback.decision_event_id ?? "none"}. Applied Event: {decisionResult.readback.applied_event_id ?? "none"}. Standing: {decisionResult.readback.standing ?? "none"}.</p>{decisionResult.refusal && <p><strong>{decisionResult.refusal.code ?? decisionResult.refusal.kind}</strong> · {decisionResult.refusal.message}</p>}</div></section>}
    {recoverable && <section className="section-block"><div className="section-heading"><div><p className="eyebrow">Exact post-commit recovery</p><h2>{recoverable}</h2></div><Button variant="secondary" onClick={previewRecover}>Review recovery</Button></div>{recoveryPreview && <div className="review-panel"><p>{recoveryPreview.warning}</p><pre className="argv-view">{recoveryPreview.argv.map((item) => JSON.stringify(item)).join(" ")}</pre><Button onClick={recover}>Recover after native confirmation</Button></div>}{recoveryResult && <p>{recoveryResult.outcome ?? recoveryResult.refusal?.message}</p>}</section>}
  </div>;
}
